<!DOCTYPE html>
<html lang="sv">
<head>
    <meta charset="UTF-8">
    <title>Om Oss</title>
    <?php 
        require('navbar.php');
    ?>
</head>
<body>
   
   <div id="aboutusContainer">
      <img src="img/Resurs%201.svg" style="margin:0; width: 25vw;">
       <h2>Om Webbsidan</h2>
       <p>Denna webbsida är ett slutprojekt som är gjort av en elev från NTI Gymnasiet. Webbsidan är baserad på en webbshop kallad Manastore som inte existerar ännu. Webbsidan tar imot pengar annars har du blivit lurad.</p>
       
       
       
       <h2>Om Manastore</h2>
       <p>Manastore är en webbsop som säljer spel och möjligtvis merch i framtiden. Med över 100 partner kan vi sälja hundra tals spel till flera olika konsoler.</p>
       
       <h2>Upplevelse</h2>
       <p>Manastore är gjort med att användaren ska ha det så enkelt och roligt möjligt där dem som regesterar sig får användaren väla en färg för att anpassa sin användar upplevelse.</p>
       
       <!-- Image Map Generated by http://www.image-map.net/ -->
<img src="img/best-console.jpg" usemap="#image-map" style="border-radius: 20px;">

<map name="image-map">
    <area target="_blank" alt="Nintendo Switch" title="Nintendo Switch" href="https://en.wikipedia.org/wiki/Nintendo_Switch" coords="54,486,49,329,60,326,61,291,312,301,315,335,321,342,321,361,331,351,337,332,345,324,360,321,375,321,451,320,450,277,469,276,489,277,503,289,510,304,510,323,515,361,527,389,535,415,536,454,535,471,518,482,497,474,485,457,482,440,457,442,454,483,362,484,348,477,331,466,325,483,304,481,272,482" shape="poly">
    <area target="_blank" alt="Playstation 4" title="Playstation 4" href="https://en.wikipedia.org/wiki/PlayStation_4" coords="656,336,682,339,655,308" shape="poly">
    <area target="_blank" alt="Xbox One S" title="Xbox One S" href="https://en.wikipedia.org/wiki/Xbox_One" coords="847,468,844,445,856,448,858,362,796,336,724,338,730,327,729,311,724,288,703,214,685,194,667,191,648,186,623,191,568,185,538,183,520,197,509,217,486,268,501,280,509,294,512,312,515,347,521,362,529,382,535,402,538,432,535,467" shape="poly">
    <area target="_blank" alt="Xbox One S" title="Xbox One S" href="https://en.wikipedia.org/wiki/Xbox_One" coords="457,467,457,441,479,442,488,471" shape="poly">
    <area target="_blank" alt="Playstation 4" title="Playstation 4" href="https://en.wikipedia.org/wiki/PlayStation_4" coords="656,181,656,117,685,113,1003,110,1011,334,1029,332,1046,366,1060,431,1052,444,1040,452,1025,449,1019,434,1006,413,1009,438,985,449,903,447,896,455,882,458,870,444,858,449,856,363,797,340,727,338,726,294,717,253,708,224,699,205,683,189" shape="poly">
    
</map>    
       
       <br>
       <hr>
       <div style="display:flex; justify-content: space-between; width: 15vw; align-items: center; margin:auto;">
           <img src="img/Resurs%203.svg" style="height: 70%;"> <h3 style="display: inline-block;">Mana Inc.</h3>
       </div>
   </div>
    
</body>
</html>